# Correlation Analysis

```{r}
data <- read.csv("data/train.csv", header = TRUE)
```
Load the data

```{r}
library(corrplot)
cor_matrix <- cor(data)
corrplot(cor_matrix, method = "circle")
```
The correlation plot shows multicollinearity between the variables.

```{r}
# find the most correlated variables
columns_to_remove <- c()
for (i in seq_len(ncol(cor_matrix) - 1)) {
  for (j in seq_len(ncol(cor_matrix) - 1)) {
    if (i > j) {
      if (abs(cor_matrix[i, j]) > 0.7) {
        print(paste(colnames(cor_matrix)[i], colnames(cor_matrix)[j],
                    cor_matrix[i, j]))
        columns_to_remove <- c(columns_to_remove, colnames(cor_matrix)[j])
      }
    }
  }
}
```

```{r}
#remove the variables that cause multicollinearity
data <- data[, !(names(data) %in% columns_to_remove)]
```

```{r}
#save the data
write.csv(data, "data/train.csv", row.names = FALSE)
```

```{r}
#Do the same for the test data
test <- read.csv("data/test.csv", header = TRUE)
test <- test[, !(names(test) %in% columns_to_remove)]
#Save the test data
write.csv(test, "data/test.csv", row.names = FALSE)
```