# Preprocessing

```{r}
# Load the data
train <- read.csv("data/train_var_selection.csv", header = TRUE, sep = ",")
test <- read.csv("data/test_var_selection.csv", header = TRUE, sep = ",")
```

## One Hot Encoding
The variables MOSTYPE and MOSHOOFD need to be one hot encoded. Actually, the variable MOSTYPE has been remove during correlation analysis since it is a specification on MOSHOOFD.
```{r}
# One hot encoding function
one_hot <- function(data, variable) {
  library(caret)
  # Convert the variable to factor
  data[[variable]] <- as.factor(data[[variable]])
  # Perform one hot encoding
  dummy <- dummyVars(" ~ .", data = data)
  data <- data.frame(predict(dummy, newdata = data))
  return(data)
}

train <- one_hot(train, "MOSHOOFD")
test <- one_hot(test, "MOSHOOFD")
```

```{r}
str(train)
```

```{r}
str(test)
```


## Scaling

```{r}
# Perform Min-Max Normalization on each column
# Each variable has a different domain, so we need to specify the normalization
# for each variable
# Apply the normalization to all the variables except MAAANTHUI, MGEMOMV
# MGEMLEEF and CARAVAN

minmax <- function(data) {
  # Domain MAANTHUI:  [1,10]
  if ("MAANTHUI" %in% colnames(data)) {
    data$MAANTHUI <- (data$MAANTHUI - 1) / (10 - 1)
  }
  # Domain MGEMOMV and MGEMLEEF:  [1,6]
  if ("MGEMOMV" %in% colnames(data)) {
    data$MGEMOMV <- (data$MGEMOMV - 1) / (6 - 1)
  }

  if ("MGEMLEEF" %in% colnames(data)) {
    data$MMGEMLEEF <- (data$MGEMLEEF - 1) / (6 - 1)
  }

  # All the other variables have domain [0, 9]
  for (i in colnames(data)) {
    if (i != "CARAVAN" &&
        i != "MAANTHUI" &&
        i != "MGEMOMV" &&
        i != "MGEMLEEF") {
      data[[i]] <- (data[[i]] - 0) / (9 - 0)
    }
  }
  return(data)
}

train <- minmax(train)
test <- minmax(test)
#save test data
write.csv(test, "data/test.csv", row.names = FALSE)
```

```{r}
```

```{r}
str(train)
```

```{r}
str(test)
```


## Balancing target variable on the training set

```{r}
# Perform ROSE oversampling
library(ROSE)
n_0 <- nrow(train[train["CARAVAN"] == 0, ])
print(n_0)
rose <- ovun.sample(CARAVAN ~ .,
                    data = train,
                    method = "over",
                    N = 2 * n_0)
#Save the data
write.csv(rose$data, "data/train_rose.csv", row.names = FALSE)
```
The CARAVAN variable in the train set is now perfectly balanced, as all things should be.

```{r}
table(rose_data$CARAVAN)
```

```{r}
str(rose_data)
```